<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.22621.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.22621.0</TargetPlatformMinVersion>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\LumaTherm.Core\LumaTherm.Core.csproj" />
    <ProjectReference Include="..\LumaTherm.Infrastructure\LumaTherm.Infrastructure.csproj" />
  </ItemGroup>
</Project>
